# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "unit-tests"
  unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bagwebsite/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      #installs dependencies to run tests
      - name: Setting up Node.js
        uses: actions/setup-node@v3

      - name: Installing dependencies
        run: npm install

      - name: Installing Playwright
        run: npx playwright install
      #runs unit tests
      - name: Running unit tests
        run: npm run test:unit
      #runs integration tests
    #   - name: Running integration tests
    #     run: npm run test
